version: "3.7"
services:
  my-sql:
    image: "mysql:${MY_SQL_VERSION}"
    container_name: assignment_my_sql
    volumes:
        - "./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    environment:
        MYSQL_ROOT_PASSWORD: changeme
    expose:
        - 3306
    networks:
        vpcbr:
            ipv4_address: 10.3.0.2
  flask:
    build: .
    container_name: assignment_task_api
    restart: always
    expose:
        - 8080
    networks:
        vpcbr:
            ipv4_address: 10.3.0.3
    depends_on:
        - my-sql
  nginx:
    image: "nginx:${NGINX_VERSION}"
    container_name: assignment_nginx
    restart: always
    volumes:
        - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
        - "8001:8001"
    networks:
        - vpcbr
    depends_on:
        - flask
networks:
  vpcbr:
    driver: bridge
    ipam:
        driver: default
        config:
            - subnet: 10.3.0.0/16
              gateway: 10.3.0.1